openapi: 3.0.2

info:
  title: Fashliy API
  version: 1.0.0
  contact:
    name: Velezer
    url: https://github.com/Velezer

externalDocs:
  description: Repository Link
  url: https://github.com/Velezer/fashliy

servers:
  - url: https://fashliy.herokuapp.com/

components:
  securitySchemes:
    jwt_token:
      type: http
      scheme: "Bearer"
  schemas:
    loginSuccess:
      type: object
      properties:
        message:
          type: string
        data:
          type: object
          properties:
            token:
              type: string

    basicMessage:
      type: object
      properties:
        message:
          type: string

    validationError:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              msg:
                type: string
              param:
                type: string
              location:
                type: string
    userLogin:
      type: object
      properties:
        email: 
          type: string
        password:
          type: string
    userRegister:
      type: object
      properties:
        email: 
          type: string
        password:
          type: string
paths:
  /:
    get:
      summary: check if server is up
      description: use this endpoint to check if server is up and running
      tags:
        - home
      responses:
        200:
          description: OK

  /api/users:
    get:
      summary: get all users
      description: admin only
      tags:
        - users
      security:
        - jwt_token: []
      responses:
        200:
          description: OK

    delete:
      summary: delete user
      description: delete based on jwt_token
      tags:
        - consultants
      security:
        - jwt_token: []
      responses:
        200:
          description: deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/basicMessage"

  /api/users/login:
    post:
      summary: login as a user
      description: for getting jwt token
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userLogin"
            example:
              name: name
              password: password

      responses:
        200:
          description: login success

  /api/users/register:
    post:
      tags:
        - users
      requestBody:
        required: true
        description: consultant data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userRegister"
            example:
              name: name
              password: password
              role: consultant
              gender: male

      responses:
        201:
          description: consultant created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/basicMessage"
        409:
          description: consultant already exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/basicMessage"
        400:
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/validationError"
